---
title: "Bachelors to PhD: Taking the leap"
author: Rushani Wijesuriya
date: '2020-10-17'
categories: []
tags:
  - PhD chat
subtitle: ''
summary: "Some important realizations I've had so far on my PhD journey"
authors: []
lastmod: '2020-10-17T20:45:57-07:00'
featured: no
disable_jquery: no
draft: true
image:
  caption: '[Photo by Timur Kozmenko on Unsplash](https://unsplash.com/photos/7gGvtQ8U4BU)'
  focal_point: ''
  preview_only: no
projects: []
---

This post was inspired by a talk I recently delivered for the [Early Career Biostatisticians’ Day](https://iscb2020.info/early-career-biostatisticians-day) at the 41st Annual ISCB conference. I recieved a lot of good feedback from those who attended, including my supervisors. So I thought it might be worth the I love teaching R Markdown. But this was not a love at first sight story. When I first started teaching with R at Oregon Health & Science University many moons ago, my students used R Markdown for their homework assignments and in-class labs. This is a great way to start for beginners, to be honest- just use it! I found that most people are not very disoriented by a file that mixes text and code; a concern I had at first and one that I've heard voiced by other educators. It seems natural to use if it is your first exposure to *all the data science things*, especially if you've never used an R script.

I did notice, though, that over the course of even just a few weeks, many of my students would reach unbearable levels of R Markdown curiosity. I would see signs of growing pains in their assignments, like how can I turn off these messages and warnings when I load packages? This is so long- how can I make it easier to find things? How can I make it look *better*?

For all learners, there comes an uncomfortable point where you simply cannot just continue to use this awesome tool without learning how to use it. And I realized when I was teaching that ultimately it was unfair of me to assume that they would just learn an entire ecosystem while I stood idly by, clutching the secrets of being an ["R Markdown Whisperer"](https://twitter.com/sharlagelfand/status/1114264529477799937?s=20) close to my chest.

Like, **why can't you just find the piñata, kid**? But more importantly, what happens when you can't? I think the risk is that learners either won't like or won't appreciate a tool that I genuinely [think would make their working lives better](https://community.rstudio.com/t/convince-me-to-start-using-r-markdown/1636/7). If I believed it was worth their time to use it, it was worth my time to teach it.
